import { gql } from "@apollo/client";

export const GET_SESSION_AND_SESSION_BOOKINGS = gql`
query getSessionAndSessionsBookings($id: ID!) {
    sessionsBookings(filters: {
      session: {
        id: {
          eq: $id
        }
      }
    }){
      data{
          id
        attributes{
          Session_booking_status
          client{
            data{
              id
              attributes{
                username
              }
            }
          }
          session{
            data{
                id
              attributes{
                start_time
                end_time
                activity{
                  data{
                    id
                    attributes{
                      title
                    }
                  }
                }
                activity_target
                tag
                type
                mode
                session_date
                workout{
                  data{
                    id
                    attributes{
                        workouttitle
                        About
                        Benifits
                        fitnessdisciplines{
                            data{
                                id
                                attributes{
                                disciplinename
                                }
                            }
                        }
                        level
                        intensity
                        calories
                        warmup
                        mainmovement
                        cooldown
                        muscle_groups{
                            data{
                                id
                                attributes{
                                    name
                                }
                            }
                        }
                        equipment_lists{
                            data{
                                id
                                attributes{
                                    name
                                }
                            }
                        }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
`